### ISSUE TITLE
Width and height usage

### ISSUE THREAD

**Issue by midzer** [jakewarren/smartcrop-cli#2]
Hi again,
just figuring out how to use this cli tool properly.

Somehow I can't use optional `width`and `height` parameters. I tried
`./smartcrop-cli --width=500 --height=500 MYFILE.jpg`
and even just
`./smartcrop-cli MYFILE.jpg`
resulting in `MYFILE.jpg` is just cropped to 1200x1200 px (from original 1600x1200).

Can you help me out whats the issue here?

Greets
midzer

**Comment by muesli** [comment]
@jakewarren I think you need to still resize the resulting crop manually, as mentioned in smartcrop's README.

**Comment by jakewarren** [comment]
@midzer As @muesli mentioned the crop from the smartcrop library will have the requested aspect ratio but overall the width and height are more of a best effort.

I thought about resizing the image however I kinda like the current implementation since it allows the user to make final adjustments. While the algorithm produces great results in the end the human user can decide the best crop for themselves.

I certainly agree that the help & possibly the parameter names should be adjusted to make that clearer.

**Comment by midzer** [comment]
Right now, I'm quite happy with actual smartcrop results :)

I'm looking for a tool to smartcrop large amounts of images. Yeah, I could manually resize each image via a script or something afterwards but having this extra functionality in one cli tool would be kinda awesome.

In fact I tried https://github.com/jwagner/smartcrop.js which produces given image dimensions on the one hand but on the other it crops differently on my sample data compared to https://github.com/muesli/smartcrop

Frankly speaking I don't see a real benefit in using current `width` and `height` parameters implementation as they produce exact same results for me whether specifying them or not.

**Comment by jakewarren** [comment]
@midzer you may be interested in https://github.com/esimov/caire. Note that the algorithm used is different, it does modify the content inside the image.
